---
abstract: 'Use TokyoTyrant for cache storage'
author:
  - 'Jiří Pavlovský <jira@getnet.cz>'
build_requires:
  CHI: 0
  Test::Class: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CHI-Driver-TokyoTyrant
provides:
  CHI::Driver::TokyoTyrant:
    file: lib/CHI/Driver/TokyoTyrant.pm
    version: 0.01
  CHI::t::Driver::TokyoTyrant:
    file: lib/CHI/t/Driver/TokyoTyrant.pm
requires:
  CHI: 0.241
  TokyoTyrant: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
